### PR TITLE
fix bag#59

### LINKED ISSUE #59: [Sign in/Sign up] The size of the “Sign in/Sign up with Google” button and the “or continue” description is not aligned on the “Login/Registration” pop-up when scaling.
**Description:** The size of the “Sign up with Google” button and the “or continue” description is not aligned on the “Login” pop-up when scaling from 125 to 150 %.

**Reproducible: always.**

**Preconditions:**
The user is not logged in.

**Steps to reproduce:**
1. Click on the “Login” button on the header of the home page.
2. Press Ctrl + scroll to scale the “Login” pop-up.
3. Take a look at the “Sign up with Google” button and the “or continue” description.

**Actual result:**
The size of the “Sign up with Google” button and the “or continue” description is not aligned on the “Login” pop-up when scaling from 125 to 150 %.

Image

**Expected result:**
The size of the “Sign up with Google” button and the “or continue” description is displayed aligned on the “Login” pop-up.

Image

### PR DESCRIPTION
**Pull request by Mygal-Alex**

### CODE REVIEW

**Review by marianamartsy — APPROVED** [review]
good 👍

**Review by AndriiNasadiuk — APPROVED** [review]
Excellend job, Alex!

**Review by LeonidShamarin — APPROVED** [review]
Good job!

**Review by vlad-khrychov — APPROVED** [review]
You should add screenshots how it works now as description of pull-request.

**Comment by Mygal-Alex** [comment]
the bug looked like this
image_2023-11-24_14-06-06
solution looks like this 
image

**Pull request merged**
