### PR TITLE
Unit test for "AppHeader" container#129

### LINKED ISSUE #129: (SP: 1) Write unit test for "AppHeader" container
### Component unit test
Unit test for "**AppHeader**" container
Scenaries descriptions:
- [ ] Should render toolbar

[Link to component](https://github.com/Space2Study-Project/Space2Study-FrontEnd/blob/develop/src/containers/layout/app-header/AppHeader.jsx)

Current coverage:
Image

### PR DESCRIPTION
**Pull request by ArtemHolikov**
close #129 

- [x] Should render Toolbar

image
image

### CODE REVIEW

**Review by marianamartsy — APPROVED** [review]
👍

**Review by AndriiNasadiuk — APPROVED** [review]
It will be good to solve mocking MUI component AppBar

**Review by LeonidShamarin — APPROVED** [review]

**Review by Mygal-Alex — APPROVED** [review]
Should we mocking MUI component?

**Review by vlad-khrychov — APPROVED** [review]
Well done

**Pull request merged**
