### PR TITLE
Added logic to Login btn

### LINKED ISSUE #62: [Login popup] Login button is clickable without entering any data in Email and Password field
**Environment:** Windows10 21H2, Chrome 112.0.5615.138
**Reproducible:** always

**Preconditions**
The user is on the client website

**Steps to reproduce**

1. Click Login button in the upper right corner of the header
2. Hover the mouse that the cursor fall on Login button and hover back outside
3. Click on Login button

**Expected result**
The Login button should be unclickable, nothing should happen

User story #32 , acceptance criteria 3
Test case https://jira.softserve.academy/browse/LVISTQB-353

### PR DESCRIPTION
**Pull request by AndriiNasadiuk**
close #62 

Знімок екрана 2023-12-04 о 21 33 12

Знімок екрана 2023-12-04 о 21 32 54

Знімок екрана 2023-12-04 о 21 32 35

Знімок екрана 2023-12-04 о 21 32 45

### CODE REVIEW

**Review by marianamartsy — APPROVED** [review]
You should add screenshots how it works now as description of pull-request.

**Review by ArtemHolikov — COMMENTED** [review]
Should we use here || instead of &&? What`s logic?

**Comment by AndriiNasadiuk** [comment]
> Should we use here || instead of &&? What`s logic?

Yes, it is inverted - button **disabled** when wrong password **or** not entered password

**Comment by AndriiNasadiuk** [comment]
> You should add screenshots how it works now as description of pull-request.

Certainly 👌

**Review by ArtemHolikov — APPROVED** [review]
Fine

**Review by LeonidShamarin — APPROVED** [review]

**Review by Mygal-Alex — APPROVED** [review]
looks good

**Review by vlad-khrychov — APPROVED** [review]

**Pull request merged**
