### PR TITLE
bugFix#104

### LINKED ISSUE #104: [Sign up] Adding full form validation
Description: validation error, fields are not selected for filling.
Reproducibility: always.

Prerequisites:
The user is not logged in.

Steps to reproduce:

Click the registration button fill in the fields with the data

Image

### PR DESCRIPTION
**Pull request by Mygal-Alex**
image
Fixed

### CODE REVIEW

**Review by LeonidShamarin — APPROVED** [review]
nice

**Review by AndriiNasadiuk — APPROVED** [review]
Much better

**Review by marianamartsy — APPROVED** [review]
ok

**Review by ArtemHolikov — APPROVED** [review]
Okay, now we have full validation

**Review by online-marathon — APPROVED** [review]

**Review by vlad-khrychov — APPROVED** [review]

**Pull request merged**
