### PR TITLE
fix bug #67 / fix guest-home-page.json

### LINKED ISSUE #67: [Home page] The title description text is not corresponded to the mockup in the home page “What can you do” block.
**Description:** The title description text is not corresponded to the mockup in the home page “What can you do” block.

**Environment:** Windows 10 x64, Microsoft Edge 112.0.1722.48, Google Chrome 112.0.5615.122.

**Reproducible:** always.

**Build found:**

**Preconditions:**
The user is not logged in.

**Steps to reproduce:**
1. Go to the client site.
2. Click on the “What can you do” button on the header of the home page.
3. Take a look at the title description text.

**Actual result:**
The title description text is not corresponded to the mockup in the home page “What can you do” block.

Image

**Expected result:**
The title description text is matched to the mockup in the home page “What can you do” block.

Image

### PR DESCRIPTION
**Pull request by Mygal-Alex**
what the bug looked
image
bug fix
image

### CODE REVIEW

**Review by marianamartsy — APPROVED** [review]
good job!

**Comment by LeonidShamarin** [comment]
good job!

**Review by LeonidShamarin — APPROVED** [review]
good job!

**Review by AndriiNasadiuk — APPROVED** [review]
ok

**Review by ArtemHolikov — APPROVED** [review]
Good job! To be honest, for a few minutes couldn`t understand where was the problem:D

**Review by vlad-khrychov — APPROVED** [review]

**Pull request merged**
