### PR TITLE
change text under button login form

### LINKED ISSUE #61: [Mentor 'Sign Up' pop-up] the text "Already have a Space2Study account? Log In" doesn't correspond the requirements
**Defect Type:** UI/Usability
**Severity:** Trivial
**Priority:** Low
**Reproducible:** Always
**Environment:** Windows 10 21H2, Chrome 110.0.5481.178

**Description:** 
The text "Already have a Space2Study account? Log In" doesn't correspond the requirements

**Preconditions:**
The web-page on the client is opened, the button "Become a Tutor" is clicked and the "Tutor Sign Up" pop-up appeared.

**Steps to reproduce:**
Take a look at the text below the "Sign Up with Google" button.

**Actual result:**
The text under "Sign Up with Google" button is "Already have a tutor account? Login!" and it is not corresponding the mockup.

Image

**Expected result:**
The text under "Sign Up with Google" button is "Already have a Space2Study account? Log In!" and is matching to mockup.

### PR DESCRIPTION
**Pull request by LeonidShamarin**
Снимок экрана (2745)
Change text under the "Sign Up with Google" button in the sign-in form of tutor

### CODE REVIEW

**Review by marianamartsy — APPROVED** [review]
👍

**Review by Mygal-Alex — APPROVED** [review]
Сool

**Review by AndriiNasadiuk — APPROVED** [review]
Everithing ok

**Review by vlad-khrychov — APPROVED** [review]
You should add screenshots how it works now as description of pull-request.

**Review by ArtemHolikov — APPROVED** [review]
Well done, Leonid! Great job! I like it!

**Pull request merged**
