### PR TITLE
[Password reset] The “Email” input field is overlapped by description text.#58

### LINKED ISSUE #58: [Password reset] The “Email” input field is overlapped by description text.
**Description:** The “Email” input field is overlapped by description text on the password reset pop-up.

**Environment:** Windows 10 x64, Microsoft Edge 115.0.1901.203, Google Chrome 116.0.5845.96.

**Reproducible:** always.

**Build found:**

**Steps to reproduce:**
1. Click on the “Login” button on the header of the home page.
2. Click on the “Forgot password?” button on the “Password reset” pop-up.
3. Take a look at the “Email” input field.

**Actual result:**
The “Email” input field is overlapped by description text on the password reset pop-up.
Overlapped

**Expected result:**
The “Email” input field is displayed aligned on the password reset pop-up.
image

**User story and test case links**
User Story User password reset #27

### PR DESCRIPTION
**Pull request by marianamartsy**
close #58
- [x] Margin edited

before

Zrzut ekranu 2023-11-24 o 13 08 51

after

Zrzut ekranu 2023-11-24 o 13 08 22

### CODE REVIEW

**Review by AndriiNasadiuk — APPROVED** [review]
Good job, Mariana)

**Review by Mygal-Alex — APPROVED** [review]
Ok

**Comment by LeonidShamarin** [comment]
Good job!

**Review by LeonidShamarin — APPROVED** [review]
Good job!

**Review by ArtemHolikov — APPROVED** [review]
Good

**Comment by vlad-khrychov** [comment]
You should add screenshots how it works now as description of pull-request.

**Review by vlad-khrychov — APPROVED** [review]

**Pull request merged**
